## Gradient Boosting Algorithm

**Input:** Data $\{(x_i, y_i)\}_{i=1}^n$, differentiable loss $L(y_i, F(x))$

**Step 1:** $F_0(x) = \underset{\gamma}{\text{argmin}} \sum_{i=1}^n L(y_i, \gamma)$

**Step 2:** for $m = 1$ to $M$:
- **(A)** $r_{im} = -\left[\frac{\partial L(y_i, F(x_i))}{\partial F(x_i)}\right]_{F(x)=F_{m-1}(x)}$, $\quad i=1,\dots,n$
- **(B)** Fit regression tree to $r_{im}$ → terminal regions $R_{jm}$, $j=1\dots J_m$
- **(C)** $\gamma_{jm} = \underset{\gamma}{\text{argmin}} \sum_{x_i \in R_{ij}} L(y_i, F_{m-1}(x_i) + \gamma)$
- **(D)** $F_m(x) = F_{m-1}(x) + \nu \sum_{j=1}^{J_m} \gamma_{jm} I(x \in R_{jm})$

**Step 3:** Output $F_M(x)$

In [5]:
import pandas as pd

In [7]:
df = pd.DataFrame(
    {'name':['thomaskutty','alan','akhil','merin','ann','suraj','kalyan','rishab'],
     'age':[30,28,35,24,43,46,32,35]}
)

In [9]:
df

          name  age
0  thomaskutty   30
1         alan   28
2        akhil   35
3        merin   24
4          ann   43
5        suraj   46
6       kalyan   32
7       rishab   35

In [12]:
df.loc[df.age>40,['age','name']]

   age   name
4   43    ann
5   46  suraj

In [13]:
df[df.age>40]

    name  age
4    ann   43
5  suraj   46